### ISSUE TITLE
Amazon API

### ISSUE THREAD

**Issue by sathiya06** [sathiya06/slash-phase3#13]
**Amazon API Endpoint Fails**
When searching for products on amazon the results are not returned.

**To Reproduce**
1. Go to home page
2. Click on search
3. Scroll down to see the empty results

**Expected behavior**
It should not be empty

**Comment by Sharatn7** [comment]
Closing this bug due to the Amazon endpoint fail error. Amazon has strict access controls and limits access to its data through authorized APIs, often at a cost. Attempting to scrape their data directly may result in errors, rejection messages, or potential violations of their terms of service.
