### ISSUE TITLE
Costco API

### ISSUE THREAD

**Issue by sathiya06** [sathiya06/slash-phase3#15]
**Costco API Endpoint Fails**
When searching for products on costco the results are not returned.

**To Reproduce**
1. Go to home page
2. Click on search
3. Scroll down to see the empty results

**Expected behavior**
It should not be empty

**Comment by aadithya-naresh** [comment]
Costco's website returns a 403 while trying to retrieve the html content using an automated tool. It might be due to Costco's access restrictions. So we will have to drop this API.
