### ISSUE TITLE
Price of the product has no currency

### ISSUE THREAD

**Issue by dhirajv2000** [sathiya06/slash-phase3#2]
Price of the product has no currency symbols and too many zerores.

**Screenshots**
<img width="137" alt="Screenshot 2023-10-13 at 4 57 45 PM" src="https://github.com/sathiya06/slash-phase3/assets/54794049/59ff0c93-fba6-4e64-ab1e-3854c07e16cb">

**Comment by sathiya06** [comment]
Added the appropriate currency symbol for the price
