### ISSUE TITLE
Cheapest product link displaying twice

### ISSUE THREAD

**Issue by dhirajv2000** [sathiya06/slash-phase3#6]
When working with the latest build the cheapest product link is displaying twice. @aadithya-naresh Kindly check this.

<img width="748" alt="Screenshot 2023-10-15 at 10 42 49 PM" src="https://github.com/sathiya06/slash-phase3/assets/54794049/5b1973e8-3055-4cd5-a719-8fbfe8b4414e">

**Comment by aadithya-naresh** [comment]
Will look into it

**Comment by Sharatn7** [comment]
Solved!!! Was caused due to an extra indentation.
